### ISSUE TITLE
How to print heap dump creation progress?

### ISSUE THREAD

**Issue by MartinLoeper** [blueconic/node-oom-heapdump#14] opened 2020-07-30 17:05 UTC
I am curious if there is a way to determine how far a heap dump creation (which is triggered by NATIVE_HOOK integration) has progressed?

We have an OOM issue in our application and installed this library. The on-demand heap dumps work flawlessly (note: little memory is used for them). However, when an OOM error is triggered, the console log "Generating Heapdump to '/var/log/nodejs/heapdumps/xxxxxxxxxx.heapsnapshot' now..." is printed and we never get the dump being written to disk. The file is created, but its size remains 0.

I think this is because 1 min after the OOM, the container is killed by health checks and container orchestration tooling. This 1 min seems not to be enough time to create and write the file to disk. That is why I would like to check if the application is actively working on creating the heap dump. If that is the case, I would look for a solution to keep the container alive after health checks failed until the heap dump creation finishes.

I looked at the [chrome-remote-interface and noticed that there are several callbacks used by heapdumpWorker.js](https://github.com/blueconic/node-oom-heapdump/blob/master/lib/heapdumpWorker.js#L31). Does anybody know if it is possible to obtain and log more information during heap dump creation?

**Comment by paulrutter** [comment] 2020-08-01 16:20
I would have to look into it some more, but the heapdumpWorker is only used for ondemand heapdumps. The OoM ones are generated from native code.
You might just run into issues with the container memory limit, as described in the readme. 
You could try running the containers with double the amount of memory to see if that resolves the heapdump being created.

**Comment by MartinLoeper** [comment] 2020-08-01 19:45
Thanks for the informative notes @paulrutter! As it turned out, the container was indeed killed by container being OOM. I increased the memory and a new issue appeared: AWS Application Load Balancing killed the container before the heap dump was fully written to disk.

That is why I look for a way to determine how long a heap dump should take or to print the progress of the heap dump to console log.

**Comment by paulrutter** [comment] 2020-08-02 05:06
Ok clear, meanwhile you could try to tune the healthcheck parameters if possible. I'll check if printing progress from native code is an option tomorrow.

**Comment by paulrutter** [comment] 2020-08-02 05:46
https://github.com/blueconic/node-oom-heapdump/blob/c1d22aab526251c832ee487d4064a9af0058ca67/lib/node_oom_heapdump_native.cc#L59 takes an argument which can handle progress. 

I found an example of this here https://github.com/node-inspector/v8-profiler/blob/8de17557028d10593a658e5c3b9a64a8099418ff/src/heap_profiler.cc#L22.

We could try to incorporate this in the codebase and just print the progress vs total in the stdout.
If i have time, I'll give it a try. A PR for this is welcome as well.

**Comment by paulrutter** [comment] 2020-08-02 21:15
I have a working version in a branch, which prints the raw progress values like this:

```
Progress of heapdump: 1550000, 2968666
Progress of heapdump: 1560000, 2968666
Progress of heapdump: 1570000, 2968666
Progress of heapdump: 1580000, 2968666
Progress of heapdump: 1590000, 2968666
Progress of heapdump: 1600000, 2968666
Progress of heapdump: 1610000, 2968666
Progress of heapdump: 1620000, 2968666
Progress of heapdump: 1630000, 2968666
Progress of heapdump: 1640000, 2968666
Progress of heapdump: 1650000, 2968666
Progress of heapdump: 1660000, 2968666
Progress of heapdump: 1670000, 2968666
Progress of heapdump: 1680000, 2968666
Progress of heapdump: 1690000, 2968666
Progress of heapdump: 1700000, 2968666
Progress of heapdump: 1710000, 2968666
Progress of heapdump: 1720000, 2968666
Progress of heapdump: 1730000, 2968666
Progress of heapdump: 1740000, 2968666
Progress of heapdump: 1750000, 2968666
Progress of heapdump: 1760000, 2968666
Progress of heapdump: 1770000, 2968666
Progress of heapdump: 1780000, 2968666
Progress of heapdump: 1790000, 2968666
Progress of heapdump: 1800000, 2968666
Progress of heapdump: 1810000, 2968666
Progress of heapdump: 1820000, 2968666
Progress of heapdump: 1830000, 2968666
Progress of heapdump: 1840000, 2968666
Progress of heapdump: 1850000, 2968666
Progress of heapdump: 1860000, 2968666
Progress of heapdump: 1870000, 2968666
Progress of heapdump: 1880000, 2968666
Progress of heapdump: 1890000, 2968666
Progress of heapdump: 1900000, 2968666
Progress of heapdump: 1910000, 2968666
```

See https://github.com/blueconic/node-oom-heapdump/tree/progress.
Can you test if this helps debugging the issue?

**Comment by MartinLoeper** [comment] 2020-08-02 23:38
Thank you @paulrutter!! That are fantastic news for troubleshooting future heap dump creations! I will try this out when I am back in office at Tuesday.

**Comment by paulrutter** [comment] 2020-08-10 08:36
@MartinLoeper Any progress on this issue?

**Comment by MartinLoeper** [comment] 2020-09-06 22:38
Sorry for the delay @paulrutter.

I tested the "2.1.0-progress.1" version and it logs the progress as expected. Good job!!
Unfortunately it did not help in debugging my initial issue, because AWS ELB killed the containers to early and there is no option to increase the duration significantly. 

I also noticed that the it takes some time until the progress reporting starts:

1. Generating Heapdump to '/var/log/nodejs/heapdumps/1599430675467.heapsnapshot' now...
2. memory increses significantly and some time goes by...
3. Progress of heapdump: 0, 62930078 .... etc.

**Comment by paulrutter** [comment] 2020-09-08 18:03
Another option might be to have a main process running in the container, which handles the healthcheck on port 80 and proxies traffic, and a forked nodejs process which actually does the work by receiving the proxied traffic.

**Comment by MartinLoeper** [comment] 2020-09-10 17:00
Thanks for reaching back and your interest for this topic. Let me elaborate a bit...

The main process inside the container is a node.js webserver. The AWS Application Load Balancer is configured to send health checks every X seconds over the traffic port and to the "/health" route.

When performance is degraded and the webserver does not respond for Y seconds to an incoming ALB health check, the ALB marks the container as unhealthy. Then, the ECS service stops the container's corresponding ECS task. 

There is only one option to delay the ECS task being killed after a stop signal was issued: the **stopTimeout**  parameter of the container definition. [1] 
However, the stopTimeout has a max value of 120 seconds. That was not enough in our case to create the whole memory dump.

I understand that we could "fake" the health checks using another process inside the docker container. However, the customer experience would be really bad because the ALB would continue to serve requests to the healthy target while the memory dump is being created.

That is why I finally gave up to analyze the heap dumps and found the underlying issue using DataDog's APM features. The bug was not a memory leak. It was caused by excessive/huge database queries (reads) which used all free RAM in the container.

Do you think there are any benefits when using a node http proxy inside the container?
What are the performance implications?

[1] https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html

**Comment by paulrutter** [comment] 2020-09-10 19:02
Thanks for your response, that makes sense. Your setup sounds logical to me, i didn't know ALB could interact with ECS to signal unhealthy containers (note to self!).

Great that you found the issue though!

The proxy solution could still help solve your issue, by using blue/green deployment. When the forked process doesn't respond, just fork another one and route the traffic to the new process. The old one can finish the heapdump (if there is enough container memory) and then exit. Maybe not ideal, but gives more flexibility.
Performance implications are hardly notable. There will always be some penalty, but our performance tests didn't notice it on average.

**Comment by paulrutter** [comment] 2020-09-11 15:48
Closing issue as it was not caused by this module. Reopen if there is more information.

**Closed by paulrutter** 2020-09-11 15:48 UTC
